### ISSUE TITLE
Fail to send to running uGet

### ISSUE THREAD

**Issue by MicroBeast** [slgobinath/uget-chrome-wrapper#13] opened 2017-02-14 18:12 UTC
**uGet Integration 1.1.6**: Installed.
**uget-chrome-wrapper 1.3.4**: Installed.
**Browsers**: Chromium (Debian repo), Vivaldi, Opera.
Linux/Debian sid amd64

It's fine if uGet it self not already running.
Neither Download detection & Context Menu "Download with uGet" are working if uGet already running.

**Comment by slgobinath** [comment] 2017-02-15 01:38
Hi,
It seems to be a strange issue. What is the uGet version?

**Comment by MicroBeast** [comment] 2017-02-15 14:39
2.0.8 from Debian repo.

**Comment by slgobinath** [comment] 2017-02-16 01:34
I am unable to reproduce this issue in my system with Linux Mint. I will test it with Debian and update you.

**Comment by MicroBeast** [comment] 2017-02-17 13:02
Okay, thank you.

**Comment by slgobinath** [comment] 2017-02-20 02:04
Hi @MicroBeast,
I couldn't reproduce this issue in my testing environment. Tested with Debian 8.7.1_x64 bit, uGet 2.0.8, uGet Integration 1.1.6, uget-chrome-wrapper 1.3.4 (Manually installed for both Google Chrome and Chromium). The browsers tested are Google Chrome and Vivaldi.

Could you please test whether this is a problem related to uGet by using the following command in terminal:

```
uget-gtk --filename="debian-live-8.7.1-amd64-gnome-desktop.iso" http://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-8.7.1-amd64-gnome-desktop.iso
```

Execute this command while uGet is not running as well as while it is running and check the behaviour and let me know the behavior.

Thanks

**Comment by MicroBeast** [comment] 2017-02-20 10:23
```
uget-gtk --filename="debian-live-8.7.1-amd64-gnome-desktop.iso" http://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-8.7.1-amd64-gnome-desktop.iso
```
Work as suppose to be. It send the link to uGet and it offer to download. Although I'm not sure why it start downloading with aria2c while the setting point to curl.

---
But nevermind that. Your script + extension work now.

After receiving your mail about testing uGet. I got nailed to "testing uGet".
So, I move old uGet profile & let uGet build fresh profile. And blam... it work.
Thing I fail to understand, all settings are same (I re-set it like the moved profile).

Anyway, I fail to realize this sooner. Might be because uGet it self was working if I add links manually.
I completely staring in wrong place, the python integration script.

I believe this not suppose to be bug could be close.

**Comment by slgobinath** [comment] 2017-02-20 11:45
Thank you for letting me know. I am closing this issue.

**Closed by slgobinath** 2017-02-20 11:45 UTC
Labels: bug
