### ISSUE TITLE
Multiple old links occasionally load en masse (20 to 30 windows)

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [slgobinath/uget-chrome-wrapper#21] opened 2017-07-31 16:09 UTC
Hi. I'm not sure yet if this is your software or uGet itself. But occasionally (every couple of weeks or something) a download will start and suddenly there are 20 to 30 new download windows on the screen. I have to terminate uGet and the problem goes away until a couple of weeks later. Latest version of the chrome add on (2.0.6) and latest uGet for Windows (2.0.9). Thanks !

**Comment by slgobinath** [comment] 2017-07-31 17:43
This is a problem with uGet Integration extension. Browsers refresh/revise their older downloads occasionally which causes to anxious uGet.

I also have faced this problem and will fix soon.

**Comment by slgobinath** [comment] 2017-08-28 14:27
@Michael-Z-Freeman,
I have released a new version of the extension: 2.0.7 with a possible fix to this problem. Since it is hard to reproduce this bug, I cannot confirm whether it really fixes this problem or not. I leave this issue open and if you face the same problem again, please do let me know.

Thanks.

**Comment by slgobinath** [comment] 2017-10-28 17:18
Closing this issue since there are no more updates on this.
I hope it has been fixed.

**Closed by slgobinath** 2017-10-28 17:18 UTC
Labels: bug, confirmed

**Comment by Michael-Z-Freeman** [comment] 2017-11-03 20:49
Thanks for the fix. Has not reoccurred so far :)
