### ISSUE TITLE
[Question] Any plans to add in compatibility for Firefox Quantum?

### ISSUE THREAD

**Issue by JamesYeoman** [slgobinath/uget-chrome-wrapper#42] opened 2017-11-12 17:04 UTC
I am currently going through my Firefox extensions and making sure I am future-proof. Are there any plans for Firefox Quantum compatibility? If not, I will get to looking for alternatives.

**Comment by bobafetthotmail** [comment] 2017-11-12 17:43
Some context:

The firefox addon isn't marked as "LEGACY" in the addon list (so it is a webextension) and the core project here runs on Chrome and derivatives (that run only webextensions), so it's reasonable to assume that the addon is compatible with Firefox Quantum  (Firefox 57).

Yet the addon page on mozilla addon site states it isn't compatible with Quantum https://addons.mozilla.org/en-US/firefox/addon/ugetintegration/

**Comment by slgobinath** [comment] 2017-11-12 17:44
You mean Firefox 57?
If so it is already supported. Already I am using this extension with my Firefox beta.

Thanks for pointing out that message. I will check that.

**Comment by slgobinath** [comment] 2017-11-12 17:47
I think other developers also have the same question. Whatever the problem is; I guarantee that I will resolve them and ensure the support to latest Firefox :-)

**Comment by DanaMW** [comment] 2017-11-12 17:51
I use it on FF 58 so I know it is compatible. Just so you can rest assured.

**Comment by slgobinath** [comment] 2017-11-14 11:20
Hi @JamesYeoman,
The problem was on Addon website and has been fixed. Please see https://github.com/mozilla/addons-server/issues/6905

**Closed by slgobinath** 2017-11-14 11:20 UTC
